---
title: "Lab 00 - Hello IDS!"
author: "YIMING LU"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

*We set up the data frame. Edit the data below to include information about your team members.*

```{r setup-tibble}
team_data <- tibble(
  name = c("Lu Junxi", "Tang Junsong", "Lu Yiming", 
           "Deng Jieming", "Guo Zeyu","Zhang Boning"),
  github_username = c("LU", "junsongtang", "YimingLuKevin", 
                      "Branddenj", "Zeyu Guo","Jona"), 
  colour = c("red","white", "black", "green", 
             "purple", "white"),
  hobby = c("fitness", "playing guitar", "weight training", 
            "photography", "basketball","gym"),
  favourite_number = c(5,7,1,3,5,3)
  )

team_data
```

### Exercise 18

*We now work on visualising our data. *

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
``` 



### Exercises 19

*Change the text of the plot title and axis labels.*

```{r labelled-bar-plot}
p1 + labs(x = "Insert text here", 
          y = "Insert text here",
          title = "Insert text here")
```



### Exercise 20

```{r new-bar-plot}
p2 <- ggplot(team_data, aes(x = hobby)) +
  geom_bar()
p2
```
